//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books_JTS
    {
        public int Book_ID { get; set; }
        public string Book_Number { get; set; }
        public string Book_Title { get; set; }
        public string Book_Publisher { get; set; }
        public string Book_AuthorName { get; set; }
        public string Book_ProdOrMfg { get; set; }
        public string Book_TrimSize { get; set; }
        public string Book_PagesEst { get; set; }
        public string Book_PagesAct { get; set; }
        public string Book_ISBN { get; set; }
        public string Book_Printer { get; set; }
        public string Book_CopyEditing { get; set; }
        public string Book_ProofReader { get; set; }
        public string Book_Indexer { get; set; }
        public string Book_Priority { get; set; }
        public string Book_Platform { get; set; }
        public Nullable<System.DateTime> Book_Received { get; set; }
        public Nullable<System.DateTime> Book_Uploaded { get; set; }
        public Nullable<System.DateTime> Book_TargetedPubDate { get; set; }
        public Nullable<System.DateTime> Book_CompletionDate { get; set; }
        public string Book_SupplierGraphics { get; set; }
        public string Book_Notes { get; set; }
        public string Book_Delivery { get; set; }
        public string Book_Status { get; set; }
        public Nullable<bool> Book_IsQuery { get; set; }
        public Nullable<bool> Book_IsFeedback { get; set; }
        public Nullable<bool> Book_IsOnHold { get; set; }
        public string Book_OnHoldRemarks { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> UsrID { get; set; }
        public string Book_Catalog { get; set; }
        public Nullable<System.DateTime> Book_ArchivalSent { get; set; }
        public string Book_Color { get; set; }
        public string Book_Layout { get; set; }
        public Nullable<bool> Book_PTRFiles { get; set; }
        public Nullable<bool> Book_DARTFiles { get; set; }
        public Nullable<int> Book_PublID { get; set; }
        public Nullable<bool> Book_FolderCreated { get; set; }
        public string Book_speInstruction { get; set; }
        public string Book_Complexity { get; set; }
        public string Book_ProofReaderbk { get; set; }
        public string Book_PtrComplexity { get; set; }
        public string Book_RevisesComplexity { get; set; }
        public string Book_Type { get; set; }
        public string Book_InvoiceStage { get; set; }
        public string Book_ProjectMgmt { get; set; }
        public string Book_EBookCon { get; set; }
        public string Book_Reprint { get; set; }
        public string Book_SpecialJob { get; set; }
        public string Book_Postage { get; set; }
        public string Book_PartInvDtl { get; set; }
        public string Book_ProofReading { get; set; }
        public string Book_ProjectManager { get; set; }
        public Nullable<System.DateTime> Book_ApprovedDate { get; set; }
        public Nullable<System.DateTime> Book_InvoiceDate { get; set; }
        public string Book_InvoiceRemarks { get; set; }
        public Nullable<long> ID { get; set; }
        public string Book_InvoiceNo { get; set; }
        public Nullable<System.DateTime> Book_ArchivalApprovedDate { get; set; }
        public string Book_ArchivalApproved { get; set; }
        public string Book_EditorName { get; set; }
        public string Book_Address1 { get; set; }
        public string Book_Address2 { get; set; }
        public string Book_Address3 { get; set; }
        public string Book_city { get; set; }
        public string Book_EditorEmail { get; set; }
        public string Book_AuthorEditorName { get; set; }
        public string Book_AuthorEdtorEmail { get; set; }
        public string Book_ProcessType { get; set; }
        public Nullable<System.DateTime> Book_ProofReturn_DueDt { get; set; }
        public string Book_ProofReturn_Name { get; set; }
        public string Book_ProofReturn_Type { get; set; }
        public string Book_Telephone { get; set; }
        public string Book_Proof_CC { get; set; }
        public string Book_Proof_BCC { get; set; }
        public Nullable<bool> Book_Proof_Approval { get; set; }
        public string Book_ProofReturn_Email { get; set; }
        public string Book_Country { get; set; }
        public string Book_PinCode { get; set; }
        public string Book_ProdEditor_Name { get; set; }
        public string Book_ProdEditor_Email { get; set; }
        public string Book_EFax { get; set; }
        public string Book_ProofReturn_Days { get; set; }
        public string Book_ProofReturn_Weeks { get; set; }
        public Nullable<bool> Book_Proof_PECC { get; set; }
        public Nullable<bool> Book_download { get; set; }
        public Nullable<System.DateTime> Book_PEIntroDt { get; set; }
        public Nullable<System.DateTime> Book_PMIntroDt { get; set; }
        public string Book_ProofSent_User { get; set; }
        public string Book_Acronym { get; set; }
        public string Book_Volume { get; set; }
        public Nullable<System.DateTime> Book_IntroEmail_SentDt { get; set; }
        public Nullable<System.DateTime> Book_ProofSendOn_Dt { get; set; }
        public string Book_Intrlno { get; set; }
        public Nullable<bool> Book_SecondPages_Approve { get; set; }
        public Nullable<System.DateTime> Book_SecondPages_SentDt { get; set; }
        public Nullable<bool> Book_FinalPages_Approve { get; set; }
        public Nullable<System.DateTime> Book_FinalPages_SentDt { get; set; }
        public Nullable<System.DateTime> Book_Tetra { get; set; }
        public string Book_EbkISBN { get; set; }
        public string Book_EPubISBN { get; set; }
        public string Book_WebPDFISBN { get; set; }
        public string Book_MobiISBN { get; set; }
        public string Book_CoverPath { get; set; }
        public string Book_FSAPath { get; set; }
        public string Book_MetaDataPath { get; set; }
        public string Book_InternalDesign { get; set; }
        public string Book_TextArea { get; set; }
        public string Book_HBKISBN { get; set; }
        public Nullable<bool> Book_Color_Insert { get; set; }
        public Nullable<bool> Book_Color_Ebook { get; set; }
        public Nullable<bool> Book_Scatter_Color { get; set; }
        public string Book_CastOff { get; set; }
        public Nullable<bool> Book_Color_Plate { get; set; }
        public Nullable<bool> Book_Dual_Edition { get; set; }
        public string Book_TSPM { get; set; }
        public Nullable<System.DateTime> Book_PEDueDt { get; set; }
        public Nullable<System.DateTime> Book_CEDueDt { get; set; }
        public Nullable<System.DateTime> Book_GFXDueDt { get; set; }
        public string Book_Location { get; set; }
        public string Book_SeriesTitle { get; set; }
        public string Book_CEType { get; set; }
        public string Book_Initial_Invoice { get; set; }
        public Nullable<bool> Book_EndDelivery_Approve { get; set; }
        public Nullable<System.DateTime> Book_EndDelivery_SentDt { get; set; }
        public string Book_KickOff_Status { get; set; }
    }
}
