//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public int Book_ID { get; set; }
        public string Book_Number { get; set; }
        public string Book_Title { get; set; }
        public Nullable<System.DateTime> Book_ReceivedDt { get; set; }
        public Nullable<System.DateTime> Book_DueDt { get; set; }
        public Nullable<int> Book_PublID { get; set; }
        public string Book_Catalog { get; set; }
        public string Book_ISBN { get; set; }
        public string Book_Platform { get; set; }
        public string Book_AuthorName { get; set; }
        public string Book_AuthorEmail { get; set; }
        public string Book_EditorName { get; set; }
        public string Book_EditorEmail { get; set; }
        public string Book_PEName { get; set; }
        public string Book_PEEmail { get; set; }
        public string Book_PMName { get; set; }
        public string Book_PMEmail { get; set; }
        public string Book_Notes { get; set; }
        public string Book_Status { get; set; }
        public string Book_SeriesTitle { get; set; }
        public string Book_Type { get; set; }
        public string Book_Category { get; set; }
        public Nullable<int> Book_Billed { get; set; }
        public Nullable<System.DateTime> Book_SentDt { get; set; }
        public string Book_Remark { get; set; }
        public string Book_Subject { get; set; }
        public string Book_Edition { get; set; }
        public string Book_Workflow { get; set; }
        public string Book_TSPM { get; set; }
        public string Book_Img { get; set; }
        public string Book_Origin { get; set; }
        public byte IsSynch { get; set; }
    }
}
