//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chapter_JTS
    {
        public int Chapter_ID { get; set; }
        public string Chapter_BookNo { get; set; }
        public Nullable<int> Chapter_BookID { get; set; }
        public string Chapter_ChapNo { get; set; }
        public string Chapter_Title { get; set; }
        public string Chapter_AuthorName { get; set; }
        public Nullable<System.DateTime> Chapter_MSReceived { get; set; }
        public Nullable<System.DateTime> Chapter_ArtReceived { get; set; }
        public string Chapter_MSPages { get; set; }
        public string Chapter_Tables { get; set; }
        public string Chapter_LineArt { get; set; }
        public string Chapter_HalfTone { get; set; }
        public string Chapter_Colour { get; set; }
        public Nullable<bool> Chapter_ReKey { get; set; }
        public Nullable<bool> Chapter_eART { get; set; }
        public string Chapter_Notes { get; set; }
        public Nullable<System.DateTime> Chapter_ToCE { get; set; }
        public Nullable<System.DateTime> Chapter_FromCE { get; set; }
        public string Chapter_FirstContact { get; set; }
        public Nullable<bool> Chapter_IsQuery { get; set; }
        public Nullable<bool> Chapter_IsFeedback { get; set; }
        public Nullable<bool> Chapter_IsOnHold { get; set; }
        public string Chapter_OnHoldRemarks { get; set; }
        public Nullable<bool> Chapter_IsCompleted { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> UsrID { get; set; }
        public string Chapter_Complexity { get; set; }
        public Nullable<int> Chapter_TotalFigures { get; set; }
        public string Chapter_SourceType { get; set; }
        public Nullable<int> Chapter_Status { get; set; }
        public Nullable<System.DateTime> Chapter_UploadedDt { get; set; }
        public Nullable<int> Chapter_StatusGFX { get; set; }
        public Nullable<System.DateTime> Chapter_CompletedDt { get; set; }
        public Nullable<System.DateTime> Chapter_ScheduledDt { get; set; }
        public Nullable<System.DateTime> Chapter_ExpectedDt { get; set; }
        public Nullable<decimal> Chapter_Schemes { get; set; }
        public Nullable<bool> Chapter_FolderCreated { get; set; }
        public string Chapter_FirstPage { get; set; }
        public string Chapter_LastPage { get; set; }
        public string Chapter_ProofPage { get; set; }
        public string Chpater_BlankPage { get; set; }
        public Nullable<int> Chapter_BlankPageCount { get; set; }
        public string Chapter_TICategory { get; set; }
        public Nullable<int> Chapter_TblLandscape { get; set; }
        public Nullable<int> Chapter_TblPotrait { get; set; }
        public string Chapter_PreULRemarks { get; set; }
        public string Chapter_TransID { get; set; }
        public string Chapter_TransStatus { get; set; }
        public Nullable<System.DateTime> Chapter_TransTime { get; set; }
        public string Chapter_TransIDGFX { get; set; }
        public string Chapter_TransStatusGFX { get; set; }
        public Nullable<System.DateTime> Chapter_TransTimeGFX { get; set; }
        public string Chapter_speInstruction { get; set; }
        public string Chapter_Invno { get; set; }
        public Nullable<System.DateTime> Chapter_InvDate { get; set; }
        public string Chapter_InvBy { get; set; }
        public string Chapter_InvSys { get; set; }
        public string Chapter_Comments { get; set; }
        public string Chapter_License { get; set; }
        public string Chapter_FigComment { get; set; }
        public Nullable<System.DateTime> Chapter_FigQueryDt { get; set; }
        public string Chapter_AuthorMail { get; set; }
        public Nullable<decimal> Chapter_Actseq { get; set; }
        public Nullable<System.DateTime> Chapter_ProofReturn_DueDt { get; set; }
        public Nullable<bool> Chapter_Proof_Approval { get; set; }
        public Nullable<bool> Chapter_Miscellaneous { get; set; }
        public string Chapter_Proof_CC { get; set; }
        public Nullable<bool> Chapter_Proof_PECC { get; set; }
        public Nullable<bool> Chapter_Proof_EDCC { get; set; }
        public string chapter_EstimateHours { get; set; }
        public string chapter_EstimateCompleteHours { get; set; }
        public string chapter_EstimateWorkingHours { get; set; }
        public string Chapter_ChapType { get; set; }
        public string Chapter_InvRemark { get; set; }
        public string Chapter_PEAllocate_Emp { get; set; }
        public Nullable<decimal> Chapter_CastOff_Pages { get; set; }
        public string Chapter_Copyright_Text { get; set; }
        public string Chapter_Copyright { get; set; }
        public string Chapter_Pagewidth_fig { get; set; }
        public string Chapter_Columnwidth_fig { get; set; }
        public string Chapter_Midwidth_fig { get; set; }
        public string Chapter_Landscape_fig { get; set; }
        public string Chapter_Noteson_fig { get; set; }
        public string Chapter_Figshare_doi { get; set; }
        public string Chapter_MSWord_Count { get; set; }
        public Nullable<int> Chapter_StatusAMS { get; set; }
        public string Chapter_TransIDAMS { get; set; }
        public string Chapter_Booking_Method { get; set; }
        public Nullable<System.DateTime> Chapter_AMSUploadedDt { get; set; }
        public string Chapter_DOI { get; set; }
        public string Chapter_ORCID { get; set; }
    }
}
