//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chapter
    {
        public int Chapter_ID { get; set; }
        public string Chapter_Number { get; set; }
        public string Chapter_Title { get; set; }
        public Nullable<int> Chapter_BookID { get; set; }
        public Nullable<System.DateTime> Chapter_ReceivedDt { get; set; }
        public Nullable<System.DateTime> Chapter_DueDt { get; set; }
        public Nullable<int> Chapter_MSPages { get; set; }
        public Nullable<int> Chapter_ColorFig { get; set; }
        public Nullable<int> Chapter_BWFig { get; set; }
        public Nullable<int> Chapter_ProofPages { get; set; }
        public Nullable<int> Chapter_Tables { get; set; }
        public string Chapter_AuthorName { get; set; }
        public string Chapter_AuthorEmail { get; set; }
        public string Chapter_Notes { get; set; }
        public Nullable<bool> Chapter_Status { get; set; }
    }
}
