//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scheduler
    {
        public int Sch_ID { get; set; }
        public Nullable<int> Sch_BookID { get; set; }
        public string Sch_Stage { get; set; }
        public Nullable<System.DateTime> Sch_PlannedDt { get; set; }
        public Nullable<System.DateTime> Sch_RevisedDt { get; set; }
        public Nullable<System.DateTime> Sch_ActualDt { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedTime { get; set; }
    }
}
