//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_WorkFlowList
    {
        public int ID { get; set; }
        public string WorkFlowName { get; set; }
        public Nullable<int> MinDays { get; set; }
        public Nullable<int> MaxDays { get; set; }
        public string PublisherList { get; set; }
        public string Description { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdatedTime { get; set; }
        public string UpdatedBy { get; set; }
        public byte IsDeleted { get; set; }
    }
}
