//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Survey
    {
        public int SurveyID { get; set; }
        public int BookID { get; set; }
        public string TextAccuracy { get; set; }
        public string Quality { get; set; }
        public string Pagination { get; set; }
        public string CopyEditing { get; set; }
        public string Delivery { get; set; }
        public string ProductAccuracy { get; set; }
        public string Response { get; set; }
        public string Communication { get; set; }
        public string ResponseTime { get; set; }
        public string Clarification { get; set; }
        public byte Submitted { get; set; }
        public int SubmittedBy { get; set; }
        public string UserType { get; set; }
        public string Comment { get; set; }
        public System.DateTime UpdatedTime { get; set; }
    }
}
