//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Instruction
    {
        public int Inst_ID { get; set; }
        public Nullable<int> BookID { get; set; }
        public string ChapterNo { get; set; }
        public string Instruction_Type { get; set; }
        public string Instruction { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedTime { get; set; }
        public Nullable<byte> IsTriggered { get; set; }
        public Nullable<byte> IsDeleted { get; set; }
    }
}
