//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Freelancer_Master
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Available { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string AvailableRemarks { get; set; }
        public string Gender { get; set; }
        public string Address { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<int> StateID { get; set; }
        public Nullable<int> CityID { get; set; }
        public string Pincode { get; set; }
        public string EmailID { get; set; }
        public string EmailID1 { get; set; }
        public string SkypeId { get; set; }
        public string MobileNo { get; set; }
        public string Specialization { get; set; }
        public string PerformanceRecord { get; set; }
        public string BankName { get; set; }
        public string AccountNo { get; set; }
        public string IFSCCode { get; set; }
        public string BranchName { get; set; }
        public string NDADocument { get; set; }
        public string PANCard { get; set; }
        public string PublisherList { get; set; }
        public string Language { get; set; }
        public string Source { get; set; }
        public string Interest { get; set; }
        public string Restriction { get; set; }
        public Nullable<byte> IsActive { get; set; }
        public string Image { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedTime { get; set; }
        public Nullable<byte> IsDeleted { get; set; }
    }
}
