//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_ForgotPassword
    {
        public int SNo { get; set; }
        public string EmailID { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string OldPassword { get; set; }
        public string NewPassword { get; set; }
        public Nullable<byte> IsMailSent { get; set; }
        public string Remarks { get; set; }
    }
}
