//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PriceGrid
    {
        public int ID { get; set; }
        public Nullable<int> PublisherID { get; set; }
        public string Services { get; set; }
        public string Complexity { get; set; }
        public Nullable<decimal> OnShoreUnitPrize { get; set; }
        public Nullable<int> OnShoreFactor { get; set; }
        public string OnShoreUnitType { get; set; }
        public Nullable<decimal> OffShoreUnitPrize { get; set; }
        public Nullable<int> OffShoreFactor { get; set; }
        public string OffShoreUnitType { get; set; }
        public Nullable<System.DateTime> UpdatedTime { get; set; }
        public string UpdatedBy { get; set; }
    }
}
