//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_FreelanceSubMaster
    {
        public int ID { get; set; }
        public Nullable<int> MainID { get; set; }
        public Nullable<int> TaskID { get; set; }
        public string Number { get; set; }
        public Nullable<int> FreelancerID { get; set; }
        public Nullable<int> TAT { get; set; }
        public Nullable<int> MSPages { get; set; }
        public Nullable<int> TypesetPages { get; set; }
        public Nullable<int> WordCount { get; set; }
        public string AllocationType { get; set; }
        public Nullable<System.DateTime> AllocationDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string FileName { get; set; }
        public string FileUploadStatus { get; set; }
        public Nullable<System.DateTime> FileUploadDate { get; set; }
        public string DownloadStatus { get; set; }
        public Nullable<System.DateTime> DownloadDate { get; set; }
        public string FinalFileName { get; set; }
        public string FinalStatus { get; set; }
        public Nullable<System.DateTime> FinalDate { get; set; }
        public byte Withdrawn { get; set; }
        public string WithdrawnRemarks { get; set; }
        public Nullable<int> TotalPages { get; set; }
        public Nullable<int> TotalWords { get; set; }
        public Nullable<int> TotalTables { get; set; }
        public Nullable<int> TotalFigures { get; set; }
        public Nullable<byte> IsInvoiced { get; set; }
        public Nullable<int> MailSentUserID { get; set; }
        public Nullable<System.DateTime> ReminderSentDate { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public int UpdatedBy { get; set; }
        public System.DateTime UpdatedTime { get; set; }
        public Nullable<byte> IsTransfer { get; set; }
        public Nullable<System.DateTime> TransferDate { get; set; }
    }
}
