//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ArchiveRestore
    {
        public int ID { get; set; }
        public Nullable<int> MainID { get; set; }
        public string Type { get; set; }
        public Nullable<System.DateTime> ArchivalRequestDt { get; set; }
        public string ArchivalStatus { get; set; }
        public Nullable<System.DateTime> ArchivalSucceedDate { get; set; }
        public string ArchivalPath { get; set; }
        public string ArchivalSize { get; set; }
        public Nullable<System.DateTime> RestoreRequestDate { get; set; }
        public string RestoreRequestStatus { get; set; }
        public Nullable<System.DateTime> RestoreSucceedDate { get; set; }
        public string RestoreSourceSize { get; set; }
        public string Restorepath { get; set; }
        public string RestoreType { get; set; }
        public Nullable<int> ArchiveRequestedBy { get; set; }
        public Nullable<int> RestoreRequestedBy { get; set; }
    }
}
