//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Signaldetails
    {
        public int SNo { get; set; }
        public string Description { get; set; }
        public string Status { get; set; }
        public string Response { get; set; }
        public Nullable<byte> IsSynch { get; set; }
        public string Type { get; set; }
        public string BookNo { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedTime { get; set; }
    }
}
