//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Feedback
    {
        public int FeedbackID { get; set; }
        public Nullable<int> PulisherID { get; set; }
        public Nullable<int> BookID { get; set; }
        public string ChapterNo { get; set; }
        public string ComplaintType { get; set; }
        public string CriticalLevel { get; set; }
        public Nullable<System.DateTime> FeedbackDate { get; set; }
        public string FeedbackTo { get; set; }
        public string Feedback { get; set; }
        public string Rootcause { get; set; }
        public string Correctiveaction { get; set; }
        public string Preventiveaction { get; set; }
        public Nullable<System.DateTime> ImplementDate { get; set; }
        public Nullable<int> Verifiedby { get; set; }
        public string Appreciation { get; set; }
        public string Type { get; set; }
        public string Attachment { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedTime { get; set; }
        public Nullable<byte> IsDeleted { get; set; }
    }
}
