//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_WorkFlowMaster
    {
        public int WorkFlowID { get; set; }
        public int ActivityID { get; set; }
        public int Sequence { get; set; }
        public Nullable<int> ParallelID { get; set; }
        public Nullable<decimal> Percentage { get; set; }
        public byte Milestone { get; set; }
        public Nullable<System.DateTime> UpdatedTime { get; set; }
        public byte IsDeleted { get; set; }
    }
}
