//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_ftpDetails
    {
        public byte SNo { get; set; }
        public string HostID { get; set; }
        public string PortNo { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
    }
}
