//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Process
    {
        public int SNo { get; set; }
        public string ProcessGroup { get; set; }
        public string ProcessName { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
    }
}
