//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_WEBAPI_Log
    {
        public int SNo { get; set; }
        public string ClientID { get; set; }
        public string WebAPI { get; set; }
        public string Parameter { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string Status { get; set; }
    }
}
