//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Freelancer_TaskPrice
    {
        public int FreelancerID { get; set; }
        public int TaskID { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Capacity { get; set; }
        public Nullable<decimal> WordPrice { get; set; }
        public Nullable<int> WordCapacity { get; set; }
        public Nullable<decimal> TablePrice { get; set; }
        public Nullable<int> TableCapacity { get; set; }
        public Nullable<decimal> FigurePrice { get; set; }
        public Nullable<int> FigureCapacity { get; set; }
    }
}
