//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_QueryTemplate
    {
        public int SNo { get; set; }
        public string TemplateName { get; set; }
        public int PublisherID { get; set; }
        public string Subject { get; set; }
        public string MailBoady { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public int UpdatedBy { get; set; }
        public System.DateTime UpdatedTime { get; set; }
    }
}
