//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ProofEmail
    {
        public int ID { get; set; }
        public Nullable<int> BookID { get; set; }
        public string FromEmail { get; set; }
        public string ToEmail { get; set; }
        public string CCEmail { get; set; }
        public string BCCEmail { get; set; }
        public string MailSubject { get; set; }
        public string MailBody { get; set; }
        public Nullable<byte> MailSent { get; set; }
        public Nullable<System.DateTime> SentDate { get; set; }
    }
}
