//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ProjectPlanning_Flow
    {
        public int PlanID { get; set; }
        public int ActivityID { get; set; }
        public decimal Percentage { get; set; }
        public decimal Days { get; set; }
        public System.DateTime ScheduleDate { get; set; }
        public Nullable<System.DateTime> RevisedScheduleDate { get; set; }
        public Nullable<System.DateTime> CompletedDate { get; set; }
        public Nullable<byte> AutoRevisedDate { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedTime { get; set; }
    }
}
