//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_WorkFlowActivities
    {
        public int ID { get; set; }
        public string Activity { get; set; }
        public decimal Percentage { get; set; }
        public byte SmartProcess { get; set; }
        public Nullable<int> Priority { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdatedTime { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<byte> IsDeleted { get; set; }
    }
}
