//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ProofDistribution_History
    {
        public long ID { get; set; }
        public int MainID { get; set; }
        public string Stage { get; set; }
        public System.DateTime EntryDate { get; set; }
        public byte SkipCE { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
    }
}
