//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_QuerySubMaster
    {
        public int ID { get; set; }
        public Nullable<int> QueryID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string QueryResponse { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string Attachment { get; set; }
    }
}
