//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_QueryMaster
    {
        public int ID { get; set; }
        public Nullable<int> MainID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string UserType { get; set; }
        public string Number { get; set; }
        public string QuerySubject { get; set; }
        public Nullable<System.DateTime> QueryDate { get; set; }
        public string Query { get; set; }
        public string QueryTo { get; set; }
        public Nullable<byte> Resolved { get; set; }
        public Nullable<System.DateTime> ResolvedDate { get; set; }
        public Nullable<System.DateTime> ReminderDate { get; set; }
        public string Solution { get; set; }
        public Nullable<int> ResolvedBy { get; set; }
        public string Priority { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
    }
}
