//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_TaskCalendar
    {
        public int SNo { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Url { get; set; }
        public string Description { get; set; }
        public string Status { get; set; }
        public string UsersList { get; set; }
        public Nullable<System.DateTime> Completed { get; set; }
        public System.DateTime CreatedTIme { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public System.DateTime UpdatedTime { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<byte> IsDeleted { get; set; }
    }
}
