//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_History
    {
        public string TableName { get; set; }
        public string ColumnName { get; set; }
        public Nullable<int> ColumnID { get; set; }
        public string OldValue { get; set; }
        public string NewValue { get; set; }
        public Nullable<System.DateTime> ModifiedDt { get; set; }
        public string HostName { get; set; }
        public int ID { get; set; }
    }
}
