//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_errorLog
    {
        public int SNo { get; set; }
        public string Page { get; set; }
        public string ErrorLog { get; set; }
        public Nullable<System.DateTime> Updatetime { get; set; }
    }
}
