//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_HelpDesk
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_HelpDesk()
        {
            this.Tbl_HelpdeskComment = new HashSet<Tbl_HelpdeskComment>();
        }
    
        public int ID { get; set; }
        public string subject { get; set; }
        public string description { get; set; }
        public Nullable<int> submitttedBy { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string priority { get; set; }
        public Nullable<System.DateTime> UpdatedTime { get; set; }
        public string Status { get; set; }
        public Nullable<byte> IsDeleted { get; set; }
        public string ResolvedBy { get; set; }
        public Nullable<int> Ticket_No { get; set; }
        public string Attachment { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_HelpdeskComment> Tbl_HelpdeskComment { get; set; }
    }
}
