//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMaster
    {
        public long UserID { get; set; }
        public string LoginID { get; set; }
        public string Password { get; set; }
        public string LoginName { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string ActiveStatus { get; set; }
        public Nullable<int> DesignationID { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<int> TeamLeadID { get; set; }
        public Nullable<int> ManagerID { get; set; }
        public Nullable<int> Coordinator1 { get; set; }
        public Nullable<int> Coordinator2 { get; set; }
        public Nullable<int> HRID { get; set; }
        public Nullable<int> RoleID { get; set; }
        public string PhoneNo { get; set; }
        public string EmailID { get; set; }
        public string Address { get; set; }
        public Nullable<int> LocationID { get; set; }
        public string BloodGroup { get; set; }
        public string WorkPhone { get; set; }
        public string WorkExtNo { get; set; }
        public string Image { get; set; }
        public string DefaultPage { get; set; }
        public string UserType { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedTime { get; set; }
        public byte IsDeleted { get; set; }
        public Nullable<int> FreelancerID { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public Nullable<int> PMBookCapacity { get; set; }
    }
}
