//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserType
    {
        public int SNo { get; set; }
        public string UserType1 { get; set; }
        public string Description { get; set; }
        public byte IsView { get; set; }
    }
}
